---
title: "Clasificacion NET PROMOTER"
author: "Izaskun Lopez-Samaniego"
date: "9 de julio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("knitr")
opts_knit$set(root.dir="./")

```

## Preparación del entorno


```{r entorno}
library(data.table)
library(caret)

ruta <-'C:/Users/izask/Modelo Parking/Modelo Parkings/src'
setwd(ruta)

source('./R_funciones.R')


t.parkings.analizar <- as.data.table(read.csv('../dat/datos_parkings.csv',
                       sep = ';', dec = ',',header = TRUE))
t.parkings.analizar <- t.parkings.analizar[,c('desc.NPS', 'Max_height.log', 
                                    'Feature_sgv',
                                    'Feature_handicapped',
                                    'n_sitios.fitness',
                                    'Feature_credit_card',
                                    'Feature_phone_coverage',
                                    'Feature_elevator',
                                    'num.meses',
                                    'tipo.aeropuerto.2b..PARK.WALK',
                                    'n_sitios.servicio.publico',
                                    'n_sitios.hospedaje',
                                    'n_sitios.hosteleria',
                                    'n_sitios.aeropuerto',
                                    'Stock',
                                    'reservas.medias.mes.mas.de.7.días',
                                    'reservas.medias.mes.entre.4.y.7.días',
                                    'reservas.medias.mes.7.horas.o.menos',
                                    'reservas.medias.mes.3.días.o.menos',
                                    'reservas.medias.mes.entre.8.y.12.horas',
                                    'reservas.medias.mes.mas.de.12.horas',
                                    'Feature_twenty_four_hours')]
t.parkings.analizar <- na.omit(t.parkings.analizar)

```



## Dividimos la muestra en casos de test y casos de training

```{r test and testing, echo=FALSE}

inTrain <- sample(1:nrow(t.parkings.analizar),
                  nrow(t.parkings.analizar)*0.3)

train.NPS  <- t.parkings.analizar[-inTrain,]
test.NPS   <- t.parkings.analizar[inTrain,]

```



## Test Modelo SVM

```{r SVM, echo=FALSE}
bootControl <- trainControl(method = "cv",
                            savePred=T)
svm.fit <- train(desc.NPS~., 
                 data= train.NPS, 
                 method = "svmRadial", tuneLength = 3, 
                 trControl = bootControl, scaled = F)

svm.fit

svm.fit$finalModel

confusionMatrix(train.NPS$desc.NPS, predict(svm.fit, train.NPS))
confusionMatrix(test.NPS$desc.NPS, predict(svm.fit, test.NPS))

```


```{r SVM Lineal, echo=FALSE}
bootControl <- trainControl(method = "cv",
                            savePred=T)
svm.fit <- train(desc.NPS ~., 
                 data= train.NPS, 
                 method = "svmLinear", tuneLength = 3, 
                 trControl = bootControl, scaled = F)

svm.fit

svm.fit$finalModel

confusionMatrix(train.NPS$desc.NPS, predict(svm.fit, train.NPS))
confusionMatrix(test.NPS$desc.NPS, predict(svm.fit, test.NPS))


```

## Test Modelo Random Forest

```{r RF, echo=FALSE}

bootControl <- trainControl(method = "cv", number = 4)
rf.fit <- train(desc.NPS ~., 
                 data= train.NPS, 
                method = "rf", tuneLength = 4, 
                trControl = bootControl, scaled = F, 
                do.trace = T, ntree = 100,
                importance=T)

rf.fit
rf.fit$finalModel

```


  - Realizamos un análisis de la importancia de las variables en cada modelo

```{r RF Imp Variables, echo=FALSE}
rfImp <- varImp(rf.fit, scale = F)
rfImp
```


## Test Modelo Redes Neuronales

```{r RN, echo=FALSE}

bootControl <- trainControl(method = "cv", number = 4)
nnet.fit <- train(desc.NPS ~., 
                 data= train.NPS, 
                 method = "nnet",
                 trControl = bootControl, scaled = T)

nnet.fit
nnet.fit$finalModel
plot(nnet.fit)
confusionMatrix(train.NPS$desc.NPS, predict(nnet.fit, train.NPS))
confusionMatrix(test.NPS$desc.NPS, predict(nnet.fit, test.NPS))


```
